services:
  loki:
    image: grafana/loki:latest
    platform: "linux/amd64"
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki_net
  
  promtail:
    image: grafana/promtail:2.9.3
    platform: "linux/amd64"
    volumes:
      - ./logs:/var/log
      - ./containers:/var/lib/docker/containers
      - ./promtail.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki_net
  
  grafana:
    container_name: grafana
    platform: "linux/amd64"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_FEATURE_TOGGLES_ENABLE=alertingSimplifiedRouting,alertingQueryAndExpressionsStepMode
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:11.4.1
    ports:
      - "3000:3000"
    networks:
      - loki_net

  python-web-app: 
    image: haidarjbeily/distroless-moscow-time-app:latest
    platform: "linux/amd64"
    container_name: python-web-app
    ports:
      - "8000:8000"
    networks:
      - loki_net 
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}"

  rust-web-app:
    image: haidarjbeily/distroless-random-quote-app:latest
    platform: "linux/amd64"
    container_name: rust-web-app
    ports:
      - "8080:8080"
    networks:
      - loki_net
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}"


networks:
  loki_net:

