apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-app
  labels:
    app: quote-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: quote-app
  template:
    metadata:
      labels:
        app: quote-app
    spec:
      containers:
      - name: quote-app
        image: haidarjbeily/distroless-moscow-time-app
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi" 